name: Bug report
description: Report a bug or unexpected behavior in YOOAdmin
title: "[BUG] "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior

  - type: input
    id: wordpress
    attributes:
      label: WordPress version

  - type: input
    id: php
    attributes:
      label: PHP version

  - type: input
    id: yooadmin
    attributes:
      label: YOOAdmin version

  - type: textarea
    id: additional
    attributes:
      label: Additional context
