name: Feature request
description: Suggest a new feature or improvement for YOOAdmin
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: Clearly explain the feature or improvement you'd like to see.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Explain the problem this feature would address.

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: If you have ideas on how this could work, share them here.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
